"""add race_md5_hex to race table

Revision ID: 0b74637fada9
Revises: 2c48c9ac4d1a
Create Date: 2022-07-15 12:51:24.991679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b74637fada9'
down_revision = '2c48c9ac4d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('race_md5_hex', sa.String(), nullable=False))
    op.create_unique_constraint('uq_race_md5_hex', 'race', ['race_md5_hex'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_race_md5_hex', 'race', type_='unique')
    op.drop_column('race', 'race_md5_hex')
    # ### end Alembic commands ###
