"""Add track_code, country, race_type

Revision ID: 0c572f4e1966
Revises: 892ada8bc20d
Create Date: 2022-05-28 21:36:30.041209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c572f4e1966'
down_revision = '892ada8bc20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('track_code', sa.String(), nullable=True))
    op.add_column('race', sa.Column('track_country', sa.String(), nullable=True))
    op.add_column('race', sa.Column('race_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_race_track_code'), 'race', ['track_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_race_track_code'), table_name='race')
    op.drop_column('race', 'race_type')
    op.drop_column('race', 'track_country')
    op.drop_column('race', 'track_code')
    # ### end Alembic commands ###
