"""odds vals to numeric

Revision ID: 10e0798206bf
Revises: 0c572f4e1966
Create Date: 2022-05-29 16:18:07.953976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e0798206bf'
down_revision = '0c572f4e1966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('race_entries', 'morning_line_odds',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='morning_line_odds::integer')
    op.alter_column('race_entries', 'profitline_odds',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='profitline_odds::integer',
               existing_nullable=True)
    op.alter_column('race_entries', 'live_odds',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='live_odds::integer',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('race_entries', 'live_odds',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('race_entries', 'profitline_odds',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('race_entries', 'morning_line_odds',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
