"""add min/max/avg reward, cost, odds to bet model

Revision ID: 2559605d42b1
Revises: 10e0798206bf
Create Date: 2022-05-29 17:27:29.360964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2559605d42b1'
down_revision = '10e0798206bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('predicted_odds', sa.Integer(), nullable=True))
    op.add_column('bets', sa.Column('min_reward', sa.Integer(), nullable=True))
    op.add_column('bets', sa.Column('max_reward', sa.Integer(), nullable=True))
    op.add_column('bets', sa.Column('avg_reward', sa.Integer(), nullable=True))
    op.add_column('bets', sa.Column('cost', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bets_cost'), 'bets', ['cost'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_cost'), table_name='bets')
    op.drop_column('bets', 'cost')
    op.drop_column('bets', 'avg_reward')
    op.drop_column('bets', 'max_reward')
    op.drop_column('bets', 'min_reward')
    op.drop_column('bets', 'predicted_odds')
    # ### end Alembic commands ###
