"""add current_race to Race

Revision ID: 2c48c9ac4d1a
Revises: c23b5feb3254
Create Date: 2022-07-11 18:25:52.197112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c48c9ac4d1a'
down_revision = 'c23b5feb3254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('current_race', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_race_current_race'), 'race', ['current_race'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_race_current_race'), table_name='race')
    op.drop_column('race', 'current_race')
    # ### end Alembic commands ###
