"""not-null for more race cols

Revision ID: 2e816e363269
Revises: b594bdce678d
Create Date: 2022-06-06 17:42:46.474754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e816e363269'
down_revision = 'b594bdce678d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('race', 'race_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('race', 'race_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('race', 'post_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('race', 'post_time_stamp',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('race', 'track_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('race', 'race_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('race', 'race_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('race', 'track_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('race', 'post_time_stamp',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('race', 'post_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('race', 'race_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('race', 'race_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
