"""Add bets, tags, race, entries

Revision ID: 892ada8bc20d
Revises: d4867f3a4c0a
Create Date: 2022-05-28 20:46:12.353581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892ada8bc20d'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_tags_id'), 'bet_tags', ['id'], unique=False)
    op.create_index(op.f('ix_bet_tags_name'), 'bet_tags', ['name'], unique=False)
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_number', sa.Integer(), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.Column('post_time_stamp', sa.BigInteger(), nullable=True),
    sa.Column('mtp', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('distance', sa.String(), nullable=True),
    sa.Column('distance_long', sa.String(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('surface_label', sa.String(), nullable=True),
    sa.Column('age_restrictions', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('wagers', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_age_restrictions'), 'race', ['age_restrictions'], unique=False)
    op.create_index(op.f('ix_race_country'), 'race', ['country'], unique=False)
    op.create_index(op.f('ix_race_id'), 'race', ['id'], unique=False)
    op.create_index(op.f('ix_race_race_date'), 'race', ['race_date'], unique=False)
    op.create_index(op.f('ix_race_status'), 'race', ['status'], unique=False)
    op.create_index(op.f('ix_race_surface'), 'race', ['surface'], unique=False)
    op.create_index(op.f('ix_race_surface_label'), 'race', ['surface_label'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('bet_type', sa.String(), nullable=True),
    sa.Column('bet_strategy_type', sa.String(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_bet_strategy_type'), 'bets', ['bet_strategy_type'], unique=False)
    op.create_index(op.f('ix_bets_bet_type'), 'bets', ['bet_type'], unique=False)
    op.create_index(op.f('ix_bets_description'), 'bets', ['description'], unique=False)
    op.create_index(op.f('ix_bets_id'), 'bets', ['id'], unique=False)
    op.create_index(op.f('ix_bets_title'), 'bets', ['title'], unique=False)
    op.create_table('race_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_pos', sa.Integer(), nullable=True),
    sa.Column('program_no', sa.String(), nullable=True),
    sa.Column('sortable_program_no', sa.Integer(), nullable=True),
    sa.Column('betting_interest', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('yob', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('where_bred', sa.String(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('medication', sa.String(), nullable=True),
    sa.Column('formatted_medication', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('overweight_amt', sa.Integer(), nullable=True),
    sa.Column('jockey_name', sa.String(), nullable=True),
    sa.Column('trainer_name', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('color_desc', sa.String(), nullable=True),
    sa.Column('sire_name', sa.String(), nullable=True),
    sa.Column('dam_name', sa.String(), nullable=True),
    sa.Column('prior_run_style', sa.String(), nullable=True),
    sa.Column('speed_pts', sa.Integer(), nullable=True),
    sa.Column('average_pace_e1', sa.Integer(), nullable=True),
    sa.Column('average_pace_e2', sa.Integer(), nullable=True),
    sa.Column('average_speed_last3', sa.Integer(), nullable=True),
    sa.Column('best_speed_at_dist', sa.Integer(), nullable=True),
    sa.Column('days_off', sa.Integer(), nullable=True),
    sa.Column('avg_class', sa.Integer(), nullable=True),
    sa.Column('last_class', sa.Integer(), nullable=True),
    sa.Column('prime_power', sa.Integer(), nullable=True),
    sa.Column('horse_claiming_price', sa.Integer(), nullable=True),
    sa.Column('power_rating', sa.Integer(), nullable=True),
    sa.Column('best_speed', sa.Integer(), nullable=True),
    sa.Column('comments_positive', sa.String(), nullable=True),
    sa.Column('comments_negative', sa.String(), nullable=True),
    sa.Column('silk_status', sa.String(), nullable=True),
    sa.Column('silk_uri', sa.String(), nullable=True),
    sa.Column('morning_line_odds', sa.String(), nullable=True),
    sa.Column('also_eligible', sa.Boolean(), nullable=True),
    sa.Column('main_track_only', sa.Boolean(), nullable=True),
    sa.Column('morning_line_fav', sa.Boolean(), nullable=True),
    sa.Column('live_odds_fav', sa.Boolean(), nullable=True),
    sa.Column('jockey_chg', sa.Boolean(), nullable=True),
    sa.Column('weight_chg', sa.Boolean(), nullable=True),
    sa.Column('weight_corrections', sa.Boolean(), nullable=True),
    sa.Column('other_change', sa.Boolean(), nullable=True),
    sa.Column('profitline_odds', sa.String(), nullable=True),
    sa.Column('live_odds', sa.String(), nullable=True),
    sa.Column('scratched', sa.Boolean(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_entries_also_eligible'), 'race_entries', ['also_eligible'], unique=False)
    op.create_index(op.f('ix_race_entries_average_speed_last3'), 'race_entries', ['average_speed_last3'], unique=False)
    op.create_index(op.f('ix_race_entries_avg_class'), 'race_entries', ['avg_class'], unique=False)
    op.create_index(op.f('ix_race_entries_best_speed_at_dist'), 'race_entries', ['best_speed_at_dist'], unique=False)
    op.create_index(op.f('ix_race_entries_betting_interest'), 'race_entries', ['betting_interest'], unique=False)
    op.create_index(op.f('ix_race_entries_color'), 'race_entries', ['color'], unique=False)
    op.create_index(op.f('ix_race_entries_dam_name'), 'race_entries', ['dam_name'], unique=False)
    op.create_index(op.f('ix_race_entries_days_off'), 'race_entries', ['days_off'], unique=False)
    op.create_index(op.f('ix_race_entries_formatted_medication'), 'race_entries', ['formatted_medication'], unique=False)
    op.create_index(op.f('ix_race_entries_id'), 'race_entries', ['id'], unique=False)
    op.create_index(op.f('ix_race_entries_jockey_chg'), 'race_entries', ['jockey_chg'], unique=False)
    op.create_index(op.f('ix_race_entries_jockey_name'), 'race_entries', ['jockey_name'], unique=False)
    op.create_index(op.f('ix_race_entries_last_class'), 'race_entries', ['last_class'], unique=False)
    op.create_index(op.f('ix_race_entries_live_odds_fav'), 'race_entries', ['live_odds_fav'], unique=False)
    op.create_index(op.f('ix_race_entries_main_track_only'), 'race_entries', ['main_track_only'], unique=False)
    op.create_index(op.f('ix_race_entries_medication'), 'race_entries', ['medication'], unique=False)
    op.create_index(op.f('ix_race_entries_morning_line_fav'), 'race_entries', ['morning_line_fav'], unique=False)
    op.create_index(op.f('ix_race_entries_owner_name'), 'race_entries', ['owner_name'], unique=False)
    op.create_index(op.f('ix_race_entries_post_pos'), 'race_entries', ['post_pos'], unique=False)
    op.create_index(op.f('ix_race_entries_power_rating'), 'race_entries', ['power_rating'], unique=False)
    op.create_index(op.f('ix_race_entries_scratched'), 'race_entries', ['scratched'], unique=False)
    op.create_index(op.f('ix_race_entries_sex'), 'race_entries', ['sex'], unique=False)
    op.create_index(op.f('ix_race_entries_sire_name'), 'race_entries', ['sire_name'], unique=False)
    op.create_index(op.f('ix_race_entries_speed_pts'), 'race_entries', ['speed_pts'], unique=False)
    op.create_index(op.f('ix_race_entries_trainer_name'), 'race_entries', ['trainer_name'], unique=False)
    op.create_index(op.f('ix_race_entries_weight_chg'), 'race_entries', ['weight_chg'], unique=False)
    op.create_index(op.f('ix_race_entries_weight_corrections'), 'race_entries', ['weight_corrections'], unique=False)
    op.create_index(op.f('ix_race_entries_where_bred'), 'race_entries', ['where_bred'], unique=False)
    op.create_index(op.f('ix_race_entries_yob'), 'race_entries', ['yob'], unique=False)
    op.create_table('bets_active_entries',
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['race_entries.id'], ),
    sa.PrimaryKeyConstraint('bet_id', 'entry_id')
    )
    op.create_table('bets_inactive_entries',
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['race_entries.id'], ),
    sa.PrimaryKeyConstraint('bet_id', 'entry_id')
    )
    op.create_table('bets_tags',
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['bet_tags.id'], ),
    sa.PrimaryKeyConstraint('bet_id', 'tag_id')
    )
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('bets_tags')
    op.drop_table('bets_inactive_entries')
    op.drop_table('bets_active_entries')
    op.drop_index(op.f('ix_race_entries_yob'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_where_bred'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_weight_corrections'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_weight_chg'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_trainer_name'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_speed_pts'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_sire_name'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_sex'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_scratched'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_power_rating'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_post_pos'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_owner_name'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_morning_line_fav'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_medication'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_main_track_only'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_live_odds_fav'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_last_class'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_jockey_name'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_jockey_chg'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_id'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_formatted_medication'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_days_off'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_dam_name'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_color'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_betting_interest'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_best_speed_at_dist'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_avg_class'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_average_speed_last3'), table_name='race_entries')
    op.drop_index(op.f('ix_race_entries_also_eligible'), table_name='race_entries')
    op.drop_table('race_entries')
    op.drop_index(op.f('ix_bets_title'), table_name='bets')
    op.drop_index(op.f('ix_bets_id'), table_name='bets')
    op.drop_index(op.f('ix_bets_description'), table_name='bets')
    op.drop_index(op.f('ix_bets_bet_type'), table_name='bets')
    op.drop_index(op.f('ix_bets_bet_strategy_type'), table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_race_surface_label'), table_name='race')
    op.drop_index(op.f('ix_race_surface'), table_name='race')
    op.drop_index(op.f('ix_race_status'), table_name='race')
    op.drop_index(op.f('ix_race_race_date'), table_name='race')
    op.drop_index(op.f('ix_race_id'), table_name='race')
    op.drop_index(op.f('ix_race_country'), table_name='race')
    op.drop_index(op.f('ix_race_age_restrictions'), table_name='race')
    op.drop_table('race')
    op.drop_index(op.f('ix_bet_tags_name'), table_name='bet_tags')
    op.drop_index(op.f('ix_bet_tags_id'), table_name='bet_tags')
    op.drop_table('bet_tags')
    # ### end Alembic commands ###
