"""add delete cascade to race_entry

Revision ID: 895e7677d006
Revises: 7858b5c6c04c
Create Date: 2022-07-07 21:01:54.228452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895e7677d006'
down_revision = '7858b5c6c04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('race_entries_race_id_fkey', 'race_entries', type_='foreignkey')
    op.create_foreign_key(None, 'race_entries', 'race', ['race_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'race_entries', type_='foreignkey')
    op.create_foreign_key('race_entries_race_id_fkey', 'race_entries', 'race', ['race_id'], ['id'])
    # ### end Alembic commands ###
