"""Add predicted_odds to race_entry

Revision ID: a5deb6a985cb
Revises: bd3c9a058b0c
Create Date: 2022-06-17 19:45:16.497313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5deb6a985cb'
down_revision = 'bd3c9a058b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race_entries', sa.Column('predicted_odds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race_entries', 'predicted_odds')
    # ### end Alembic commands ###
