"""support bet sub_bets

Revision ID: b594bdce678d
Revises: 0c1578883760
Create Date: 2022-05-29 22:55:56.758005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b594bdce678d'
down_revision = '0c1578883760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bets', 'bets', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bets', type_='foreignkey')
    op.drop_column('bets', 'parent_id')
    # ### end Alembic commands ###
