"""add bet_md5_hex to bet

Revision ID: b6ceecb03e1e
Revises: 0b74637fada9
Create Date: 2022-07-15 18:31:22.702676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ceecb03e1e'
down_revision = '0b74637fada9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('bet_md5_hex', sa.String(), nullable=False))
    op.create_unique_constraint('uq_bet_md5_hex', 'bets', ['bet_md5_hex'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bet_md5_hex', 'bets', type_='unique')
    op.drop_column('bets', 'bet_md5_hex')
    # ### end Alembic commands ###
